---

pipeline:
  build:
    commands:
      - /root/entrypoint.sh
      - sbt clean test
    image: quay.io/ukhomeofficedigital/scala-sbt:v0.4.0
    environment:
      - ARTIFACTORY_USERNAME=regt-build-bot
    secrets:
      - ARTIFACTORY_PASSWORD
    when:
      event: push

  publish_npm:
    commands:
      - npm i
      - npm test
      - npm publish
    image: node:8
    secrets:
      - npm_config__auth
      - npm_config_registry
      - npm_config_email
    environment:
      - NPM_CONFIG_ALWAYS_AUTH=true
    when:
      event: push
      branch: master

  publish:
    commands:
      - /root/entrypoint.sh
      - sbt publish
    image: quay.io/ukhomeofficedigital/scala-sbt:v0.3.1
    environment:
      - ARTIFACTORY_SERVER=https://artifactory.digital.homeoffice.gov.uk/
      - ARTIFACTORY_USERNAME=regt-build-bot
    secrets:
      - ARTIFACTORY_PASSWORD
    when:
      event: push
      branch: master

  publish_tag:
    commands:
      - /root/entrypoint.sh
      - sbt "set version := \"$${DRONE_TAG}\"" publish
    image: quay.io/ukhomeofficedigital/scala-sbt:v0.3.1
    environment:
      - ARTIFACTORY_SERVER=https://artifactory.digital.homeoffice.gov.uk/
      - ARTIFACTORY_USERNAME=regt-build-bot
    secrets:
      - ARTIFACTORY_PASSWORD
    when:
      event: tag
