---

pipeline:
  build_publish_npm:
   commands:
     - bash -c ./set-node-package-version.sh
     - npm i
     - npm run env
     # - npm test
     # - npm publish
   image: node:8
   secrets:
     - npm_config__auth
     - npm_config_registry
     - npm_config_email
   environment:
     - NPM_CONFIG_ALWAYS_AUTH=true
   when:
     event:
       - push
       - tag
     branch: master

  build_scala:
    commands:
      - /root/entrypoint.sh
      - git fetch --tags
      - sbt clean test
    image: quay.io/ukhomeofficedigital/scala-sbt:v0.4.0
    environment:
      - ARTIFACTORY_USERNAME=regt-build-bot
    secrets:
      - ARTIFACTORY_PASSWORD
    when:
      event:
        - push
        - tag

  publish_scala:
    commands:
      - /root/entrypoint.sh
      - git reset --hard
      - sbt clean +publish
    image: quay.io/ukhomeofficedigital/scala-sbt:v0.3.1
    environment:
      - ARTIFACTORY_SERVER=https://artifactory.digital.homeoffice.gov.uk/
      - ARTIFACTORY_USERNAME=regt-build-bot
    secrets:
      - ARTIFACTORY_PASSWORD
    when:
      event:
        - push
        - tag
      branch: master
